# -*- coding: utf-8 -*-


class AiostemError(Exception):
    'Base error for exceptions generated by this library.'


class ControllerError(AiostemError):
    'Base error raised by the controller'


class ProtocolError(AiostemError):
    'Base error for communication issues with the controller.'
