class AiostemError(Exception):
    """Base error for exceptions generated by this library."""


class ControllerError(AiostemError):
    """Base error raised by the controller."""


class ProtocolError(AiostemError):
    """Base error for communication issues with the controller."""


class MessageError(AiostemError):
    """Results of a bad manipulation of a received Message."""


class ResponseError(AiostemError):
    """Response message is an error (status is provided)."""

    def __init__(self, status: int, message: str) -> None:
        """Create a new response error with an integer status and a message."""
        super().__init__(message)
        self._status = status

    @property
    def status(self) -> int:
        """Response status that generated this message."""
        return self._status
